language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8

before_script:
  - npm install -g yarn
  - yarn install

script:
  - yarn run build
  - yarn run build-tests
  - yarn run test
  - # yarn run coveralls
